"""add Category.sub_category

Revision ID: 639063ce1d55
Revises: cd2df26f0026
Create Date: 2019-11-26 21:28:36.494218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639063ce1d55'
down_revision = 'cd2df26f0026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'parent_id')
    # ### end Alembic commands ###
