"""add Comment.reply

Revision ID: 9b356a815da2
Revises: df35517b3f21
Create Date: 2019-11-26 15:33:59.360507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b356a815da2'
down_revision = 'df35517b3f21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'reply_id')
    # ### end Alembic commands ###
