"""empty message

Revision ID: f4fcfd16c7ed
Revises: 639063ce1d55
Create Date: 2019-11-27 14:25:50.170588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fcfd16c7ed'
down_revision = '639063ce1d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'categories', 'categories', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    # ### end Alembic commands ###
